-- Revert ofact:init from pg

BEGIN;

DROP DOMAIN IF EXISTS pass CASCADE;

DROP DOMAIN IF EXISTS mail CASCADE;

DROP DOMAIN IF EXISTS pcode CASCADE;

DROP TABLE IF EXISTS invoice_line CASCADE;

DROP TABLE IF EXISTS invoice CASCADE;

DROP TABLE IF EXISTS product CASCADE;

DROP TABLE IF EXISTS visitor CASCADE;

COMMIT;